name: isar_test

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  intl: ^0.19.0
  isar_community: any
  isar_community_flutter_libs: any
  json_annotation: ^4.7.0
  meta: ^1.8.0
  path: ^1.8.2
  path_provider: ^2.0.10
  test: ^1.21.4
  test_api: ^0.5.1

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  isar_community_generator: any
  json_serializable: ^6.3.1
  very_good_analysis: ^3.0.1

dependency_overrides:
  isar_community:
    path: ../isar_community
  isar_community_flutter_libs:
    path: ../isar_community_flutter_libs

  isar_community_generator:
    path: ../isar_community_generator
